import type { ReactNode } from 'react';
import { AlertCircle, CheckCircle2, Info, LoaderCircle, Plus } from 'lucide-react';

export function PageHeading({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: ReactNode }) {
  return <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div>{eyebrow && <p className="mb-2 text-[10px] font-bold uppercase tracking-[.18em] text-brand-600">{eyebrow}</p>}<h1 className="text-2xl font-bold tracking-tight text-ink sm:text-[28px]">{title}</h1>{description && <p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{description}</p>}</div>{action}</div>;
}
export function Card({ children, className = '' }: { children: ReactNode; className?: string }) { return <section className={`rounded-2xl border border-line bg-white shadow-soft ${className}`}>{children}</section>; }
export function CardHeader({ title, description, action }: { title: string; description?: string; action?: ReactNode }) { return <div className="flex items-start justify-between gap-4 border-b border-line px-5 py-4"><div><h2 className="text-sm font-bold text-ink">{title}</h2>{description && <p className="mt-1 text-xs text-slate-500">{description}</p>}</div>{action}</div>; }
export function Button({ children, variant = 'primary', size = 'md', className = '', ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'ghost' | 'danger'; size?: 'sm' | 'md' }) {
  const variants = { primary: 'bg-ink text-white hover:bg-slate-800 disabled:bg-slate-300', secondary: 'border border-line bg-white text-slate-700 hover:bg-slate-50', ghost: 'text-slate-600 hover:bg-slate-100', danger: 'bg-rose-600 text-white hover:bg-rose-700' };
  return <button className={`inline-flex items-center justify-center gap-2 rounded-xl font-semibold transition disabled:cursor-not-allowed ${size === 'sm' ? 'px-3 py-2 text-xs' : 'px-4 py-2.5 text-sm'} ${variants[variant]} ${className}`} {...props}>{children}</button>;
}
export function Input({ label, hint, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label?: string; hint?: string }) { return <label className="block space-y-1.5"><span className="text-xs font-semibold text-slate-700">{label}</span><input className="field-input" {...props} />{hint && <span className="block text-[11px] text-slate-400">{hint}</span>}</label>; }
export function Select({ label, children, ...props }: React.SelectHTMLAttributes<HTMLSelectElement> & { label?: string }) { return <label className="block space-y-1.5"><span className="text-xs font-semibold text-slate-700">{label}</span><select className="field-input" {...props}>{children}</select></label>; }
export function TextArea({ label, ...props }: React.TextareaHTMLAttributes<HTMLTextAreaElement> & { label?: string }) { return <label className="block space-y-1.5"><span className="text-xs font-semibold text-slate-700">{label}</span><textarea className="field-input min-h-[92px] resize-y" {...props} /></label>; }
export function Notice({ tone = 'info', title, children }: { tone?: 'info' | 'warning' | 'danger' | 'success'; title?: string; children: ReactNode }) {
  const styles = { info: 'border-brand-100 bg-brand-50 text-brand-700', warning: 'border-amber-200 bg-amber-50 text-amber-900', danger: 'border-rose-200 bg-rose-50 text-rose-800', success: 'border-emerald-200 bg-emerald-50 text-emerald-800' };
  const Icon = tone === 'success' ? CheckCircle2 : tone === 'info' ? Info : AlertCircle;
  return <div className={`flex gap-3 rounded-2xl border p-4 ${styles[tone]}`}><Icon size={18} className="mt-0.5 shrink-0" /><div className="text-xs leading-5"><div className="font-bold">{title || (tone === 'danger' ? 'Needs attention' : tone === 'warning' ? 'Review required' : tone === 'success' ? 'Done' : 'Information')}</div><div className="mt-1">{children}</div></div></div>;
}
export function Loading({ label = 'Loading data' }: { label?: string }) { return <div className="flex min-h-[180px] items-center justify-center gap-2 text-sm text-slate-500"><LoaderCircle className="animate-spin" size={18} />{label}</div>; }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <div className="flex min-h-[220px] flex-col items-center justify-center px-6 py-12 text-center"><div className="mb-4 flex h-12 w-12 items-center justify-center rounded-2xl bg-slate-100 text-slate-500"><Info size={20} /></div><h3 className="text-sm font-bold text-ink">{title}</h3><p className="mt-2 max-w-md text-xs leading-5 text-slate-500">{description}</p>{action && <div className="mt-5">{action}</div>}</div>; }
export function Pill({ children, tone = 'slate' }: { children: ReactNode; tone?: 'slate' | 'green' | 'amber' | 'blue' | 'rose' }) { const colors = { slate: 'bg-slate-100 text-slate-600', green: 'bg-emerald-50 text-emerald-700', amber: 'bg-amber-50 text-amber-700', blue: 'bg-brand-50 text-brand-700', rose: 'bg-rose-50 text-rose-700' }; return <span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-bold ${colors[tone]}`}>{children}</span>; }
export function SectionTitle({ title, sub, action }: { title: string; sub?: string; action?: ReactNode }) { return <div className="mb-4 flex items-center justify-between gap-3"><div><h2 className="text-sm font-bold text-ink">{title}</h2>{sub && <p className="mt-1 text-xs text-slate-500">{sub}</p>}</div>{action}</div>; }
export function PlusButton({ onClick, children = 'Add record' }: { onClick: () => void; children?: ReactNode }) { return <Button onClick={onClick}><Plus size={16} />{children}</Button>; }
