import { useCallback, useEffect, useMemo, useState } from 'react';
import { Pencil, RefreshCw, Search, Trash2, X } from 'lucide-react';
import { api, getErrorMessage } from '../lib/api';
import { useAuth } from '../lib/auth';
import { Button, Card, EmptyState, Input, Notice, PageHeading, Pill, Select, TextArea } from '../components/ui';

type Field = { name: string; label: string; type?: 'text' | 'email' | 'number' | 'date' | 'json' | 'list' | 'boolean'; required?: boolean; hint?: string; placeholder?: string };
type ResourceDefinition = { endpoint: string; title: string; description: string; columns: string[]; fields: Field[] };
const definitions: Record<string, ResourceDefinition> = {
  departments: { endpoint: 'departments', title: 'Departments', description: 'Organize academic ownership and department-level scheduling.', columns: ['code', 'name', 'description'], fields: [{ name: 'code', label: 'Department code', required: true }, { name: 'name', label: 'Department name', required: true }, { name: 'description', label: 'Description' }] },
  'academic-years': { endpoint: 'academicYears', title: 'Academic years', description: 'Manage academic calendar periods used by semester and timetable versions.', columns: ['name', 'startDate', 'endDate', 'status'], fields: [{ name: 'name', label: 'Academic year name', required: true, placeholder: 'AY 2026–27' }, { name: 'startDate', label: 'Start date', type: 'date', required: true }, { name: 'endDate', label: 'End date', type: 'date', required: true }, { name: 'status', label: 'Status', placeholder: 'planned / active / completed' }] },
  semesters: { endpoint: 'semesters', title: 'Semesters', description: 'Configure working days, periods, breaks, and reference-verification status independently for each semester.', columns: ['semesterName', 'semesterNumber', 'status', 'configurationVerified'], fields: [{ name: 'departmentId', label: 'Department ObjectId', required: true }, { name: 'academicYearId', label: 'Academic year ObjectId', required: true }, { name: 'semesterNumber', label: 'Semester number', type: 'number', required: true }, { name: 'semesterName', label: 'Semester name', required: true }, { name: 'workingDays', label: 'Working days', type: 'list', hint: 'Comma-separated, e.g. Monday,Tuesday,Wednesday' }, { name: 'timeSlots', label: 'Time slots JSON', type: 'json', placeholder: '[{"periodIndex":1,"startTime":"09:15","endTime":"10:15"}]' }, { name: 'breakConfiguration', label: 'Breaks JSON', type: 'json', placeholder: '[{"name":"Lunch","startTime":"13:30","endTime":"14:15"}]' }, { name: 'configurationVerified', label: 'Reference configuration verified', type: 'boolean' }, { name: 'sourceNotes', label: 'Verification notes' }] },
  faculty: { endpoint: 'faculty', title: 'Faculty', description: 'Manage faculty identity, teaching capacity, and availability data.', columns: ['employeeId', 'name', 'email', 'designation', 'maxWeeklyPeriods'], fields: [{ name: 'employeeId', label: 'Employee ID', required: true }, { name: 'name', label: 'Full name', required: true }, { name: 'email', label: 'Email', type: 'email', required: true }, { name: 'departmentId', label: 'Department ObjectId', required: true }, { name: 'designation', label: 'Designation' }, { name: 'maxDailyPeriods', label: 'Maximum daily periods', type: 'number' }, { name: 'maxWeeklyPeriods', label: 'Maximum weekly periods', type: 'number' }, { name: 'availability', label: 'Available windows JSON', type: 'json', placeholder: '[]' }, { name: 'unavailableSlots', label: 'Unavailable windows JSON', type: 'json', placeholder: '[]' }] },
  subjects: { endpoint: 'subjects', title: 'Subjects', description: 'Maintain contact hours, course type, duration, and eligible teaching resources.', columns: ['subjectCode', 'subjectName', 'shortName', 'courseType', 'weeklyPeriods', 'needsVerification'], fields: [{ name: 'subjectCode', label: 'Subject code', required: true }, { name: 'subjectName', label: 'Subject name', required: true }, { name: 'shortName', label: 'Short name', required: true }, { name: 'departmentId', label: 'Department ObjectId', required: true }, { name: 'semesterId', label: 'Semester ObjectId', required: true }, { name: 'courseType', label: 'Course type', required: true, placeholder: 'Theory / Lab / Tutorial / Project' }, { name: 'weeklyPeriods', label: 'Weekly periods', type: 'number', required: true }, { name: 'lectureDuration', label: 'Lecture duration', type: 'number' }, { name: 'labDuration', label: 'Lab duration', type: 'number' }, { name: 'requiresLab', label: 'Requires laboratory', type: 'boolean' }, { name: 'eligibleClassrooms', label: 'Eligible classroom ObjectIds', type: 'list' }, { name: 'eligibleFaculty', label: 'Eligible faculty ObjectIds', type: 'list' }, { name: 'needsVerification', label: 'Needs administrator verification', type: 'boolean' }] },
  batches: { endpoint: 'batches', title: 'Batches & lab groups', description: 'Differentiate semester sections from practical subgroups such as W1–W4 and D1–D2.', columns: ['batchCode', 'batchName', 'batchType', 'studentCount', 'needsVerification'], fields: [{ name: 'batchCode', label: 'Batch code', required: true }, { name: 'batchName', label: 'Batch name', required: true }, { name: 'semesterId', label: 'Semester ObjectId', required: true }, { name: 'studentCount', label: 'Student count', type: 'number' }, { name: 'batchType', label: 'Batch type', placeholder: 'standard / lab-group / elective / common' }, { name: 'parentBatchId', label: 'Parent batch ObjectId' }, { name: 'needsVerification', label: 'Needs administrator verification', type: 'boolean' }] },
  classrooms: { endpoint: 'classrooms', title: 'Classrooms & labs', description: 'Track room capacity, room type, equipment, and availability.', columns: ['roomCode', 'roomName', 'roomType', 'capacity'], fields: [{ name: 'roomCode', label: 'Room code', required: true }, { name: 'roomName', label: 'Room name', required: true }, { name: 'roomType', label: 'Room type', required: true, placeholder: 'Lecture / Laboratory / Seminar' }, { name: 'capacity', label: 'Capacity', type: 'number', required: true }, { name: 'equipment', label: 'Equipment', type: 'list' }, { name: 'departmentId', label: 'Department ObjectId' }, { name: 'availability', label: 'Availability JSON', type: 'json', placeholder: '[]' }] },
  assignments: { endpoint: 'assignments', title: 'Teaching assignments', description: 'Connect subjects, faculty, student groups, room requirements, and weekly periods.', columns: ['subjectId', 'facultyId', 'batchId', 'weeklyPeriods', 'sessionDuration', 'needsVerification'], fields: [{ name: 'semesterId', label: 'Semester ObjectId', required: true }, { name: 'subjectId', label: 'Subject ObjectId', required: true }, { name: 'facultyId', label: 'Faculty ObjectId', required: true }, { name: 'batchId', label: 'Batch ObjectId (blank for common class)' }, { name: 'classroomId', label: 'Fixed classroom ObjectId (optional)' }, { name: 'weeklyPeriods', label: 'Weekly periods', type: 'number', required: true }, { name: 'sessionDuration', label: 'Consecutive periods per session', type: 'number', required: true }, { name: 'courseType', label: 'Course type', required: true, placeholder: 'Theory / Lab / Tutorial / Project' }, { name: 'needsVerification', label: 'Needs administrator verification', type: 'boolean' }] }
};
const showValue = (value: any) => value == null ? '—' : typeof value === 'object' ? JSON.stringify(value) : String(value);

export function Resources({ page }: { page: string }) {
  const definition = definitions[page];
  const { user } = useAuth();
  const [records, setRecords] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [search, setSearch] = useState('');
  const [query, setQuery] = useState('');
  const [modal, setModal] = useState(false);
  const [editing, setEditing] = useState<any>(null);
  const [form, setForm] = useState<Record<string, any>>({});
  const [saving, setSaving] = useState(false);
  const canEdit = user?.role === 'Admin' || user?.role === 'HOD';
  const load = useCallback(async () => {
    if (!definition) return;
    setLoading(true); setError('');
    try { const response = await api.get(`/${definition.endpoint}`, { params: { limit: 100, ...(query ? { search: query } : {}) } }); setRecords(response.data.data); }
    catch (reason) { setError(getErrorMessage(reason)); }
    finally { setLoading(false); }
  }, [definition, query]);
  useEffect(() => { void load(); }, [load]);
  const rows = useMemo(() => records, [records]);
  const openCreate = () => { setEditing(null); setForm({}); setModal(true); };
  const openEdit = (record: any) => { setEditing(record); setForm(Object.fromEntries(definition.fields.map(field => [field.name, field.type === 'json' ? JSON.stringify(record[field.name] ?? [], null, 2) : field.type === 'list' ? (record[field.name] || []).map((value: any) => typeof value === 'object' ? value._id : value).join(', ') : field.type === 'date' && record[field.name] ? String(record[field.name]).slice(0, 10) : field.type === 'boolean' ? Boolean(record[field.name]) : record[field.name] ?? '']))); setModal(true); };
  const submit = async (event: React.FormEvent) => {
    event.preventDefault(); setSaving(true); setError('');
    try {
      const payload: any = {};
      for (const field of definition.fields) {
        const value = form[field.name];
        if (field.type === 'boolean') { if (value === true) payload[field.name] = true; else if (editing && value === false) payload[field.name] = false; continue; }
        if ((value == null || value === '') && !field.required) continue;
        if (field.type === 'number') payload[field.name] = Number(value);
        else if (field.type === 'json') payload[field.name] = JSON.parse(value || '[]');
        else if (field.type === 'list') payload[field.name] = String(value || '').split(',').map(item => item.trim()).filter(Boolean);
        else payload[field.name] = value;
      }
      if (editing) await api.put(`/${definition.endpoint}/${editing._id}`, payload); else await api.post(`/${definition.endpoint}`, payload);
      setModal(false); await load();
    } catch (reason: any) { setError(reason?.response?.data?.error?.message || getErrorMessage(reason)); }
    finally { setSaving(false); }
  };
  const deactivate = async (record: any) => {
    if (!window.confirm(`Deactivate ${record.name || record.subjectName || record.batchName || record.roomName || record.employeeId || 'this record'}? Existing timetable history will be preserved.`)) return;
    try { await api.delete(`/${definition.endpoint}/${record._id}`); await load(); } catch (reason) { setError(getErrorMessage(reason)); }
  };
  if (!definition) return <Notice tone="danger">This resource page is not configured.</Notice>;
  return <>
    <PageHeading eyebrow="Academic setup" title={definition.title} description={definition.description} action={canEdit ? <Button onClick={openCreate}>+ Add record</Button> : undefined} />
    {error && <div className="mb-4"><Notice tone="danger">{error}</Notice></div>}
    <Card>
      <div className="flex flex-col gap-3 border-b border-line p-4 sm:flex-row sm:items-center sm:justify-between"><div className="text-xs font-semibold text-slate-500">{rows.length} records · changes are audited and deletes are soft-deactivated</div><form onSubmit={event => { event.preventDefault(); setQuery(search); }} className="flex gap-2"><div className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input className="field-input min-w-[210px] pl-9" placeholder="Search records" value={search} onChange={event => setSearch(event.target.value)} /></div><Button variant="secondary" size="sm" type="submit">Search</Button><Button variant="ghost" size="sm" type="button" onClick={() => { setSearch(''); setQuery(''); }}><RefreshCw size={14} /></Button></form></div>
      {loading ? <div className="p-10 text-center text-sm text-slate-400">Loading records…</div> : rows.length === 0 ? <EmptyState title={`No ${definition.title.toLowerCase()} found`} description={query ? 'Try a different search term.' : 'Add a record or import it from an Excel workbook to get started.'} action={canEdit && <Button onClick={openCreate}>Add first record</Button>} /> : <div className="overflow-x-auto"><table className="min-w-full text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase tracking-wide text-slate-500"><tr>{definition.columns.map(column => <th key={column} className="px-5 py-3 font-bold">{column.replace(/([A-Z])/g, ' $1')}</th>)}<th className="px-5 py-3 font-bold">Status</th>{canEdit && <th className="px-5 py-3 text-right font-bold">Actions</th>}</tr></thead><tbody className="divide-y divide-line">{rows.map(record => <tr key={record._id} className="hover:bg-slate-50/70">{definition.columns.map(column => <td key={column} className="max-w-[260px] px-5 py-3.5 text-slate-700"><span className="block truncate" title={showValue(record[column])}>{showValue(record[column])}</span></td>)}<td className="px-5 py-3.5"><Pill tone={record.active === false || record.status === 'archived' ? 'rose' : record.configurationVerified ? 'green' : 'blue'}>{record.active === false ? 'inactive' : record.status || (record.configurationVerified === false ? 'verify setup' : 'active')}</Pill></td>{canEdit && <td className="px-5 py-3.5 text-right"><div className="inline-flex gap-1"><button className="icon-button" title="Edit" onClick={() => openEdit(record)}><Pencil size={14} /></button><button className="icon-button text-rose-500" title="Deactivate" onClick={() => deactivate(record)}><Trash2 size={14} /></button></div></td>}</tr>)}</tbody></table></div>}
    </Card>
    {modal && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" role="dialog" aria-modal="true"><div className="max-h-[90vh] w-full max-w-2xl overflow-hidden rounded-2xl bg-white shadow-xl"><div className="flex items-center justify-between border-b border-line px-5 py-4"><div><h2 className="text-sm font-bold text-ink">{editing ? `Edit ${definition.title.slice(0, -1)}` : `Add ${definition.title.slice(0, -1)}`}</h2><p className="mt-1 text-[11px] text-slate-500">Related records can also be loaded with the Excel import workflow.</p></div><button onClick={() => setModal(false)} className="icon-button" aria-label="Close"><X size={18} /></button></div><form onSubmit={submit} className="max-h-[calc(90vh-68px)] overflow-y-auto"><div className="grid gap-4 p-5 sm:grid-cols-2">{definition.fields.map(field => <div key={field.name} className={field.type === 'json' ? 'sm:col-span-2' : ''}>{field.type === 'json' ? <TextArea label={field.label} required={field.required} placeholder={field.placeholder} value={form[field.name] ?? ''} onChange={event => setForm(current => ({ ...current, [field.name]: event.target.value }))} /> : field.type === 'boolean' ? <label className="flex items-center gap-3 rounded-xl border border-line px-3 py-3"><input type="checkbox" checked={Boolean(form[field.name])} onChange={event => setForm(current => ({ ...current, [field.name]: event.target.checked }))} className="h-4 w-4 accent-brand-600" /><span className="text-xs font-semibold text-slate-700">{field.label}</span></label> : <Input label={field.label} type={field.type === 'number' ? 'number' : field.type === 'date' ? 'date' : field.type === 'email' ? 'email' : 'text'} required={field.required} min={field.type === 'number' ? 0 : undefined} placeholder={field.placeholder} hint={field.hint} value={form[field.name] ?? ''} onChange={event => setForm(current => ({ ...current, [field.name]: event.target.value }))} />}</div>)}</div>{error && <div className="px-5 pb-4"><Notice tone="danger">{error}</Notice></div>}<div className="flex justify-end gap-2 border-t border-line bg-slate-50 px-5 py-4"><Button type="button" variant="secondary" onClick={() => setModal(false)}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? 'Saving…' : editing ? 'Save changes' : 'Create record'}</Button></div></form></div></div>}
  </>;
}
